baseurl: "/"
languageCode: "en-us"
title: "March Madness!"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

menu:
  main:
    - name: Leaderboard
      url: ""
      weight: 1
    - name: Rules
      url: "rules/"
      weight: 2
    - name: Picks
      url: "picks/"
      weight: 3

params:
  description: "A website built through Hugo and blogdown."
  footer: ""

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
